calendarSchool/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('', include('codes.urls', namespace="codes")),
    path('auth/', include('social_django.urls', namespace='social')),
]

codes/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'codes'

urlpatterns = [
    path('', views.index, name="index"),
    path('c/<str:q>', views.display_class, name="classDetail"),
    path('codes', views.codes, name="codes"),
    path('soumission', views.soumission, name="soumission"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('classes/', views.user_classes, name="classes")
]

codes/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.dispatch import receiver


# pylint: disable=no-member

# Create your models here.
GROUPES_CHOICES = [
    ("TOUS","Tous"),
    ("3R","3R"),
    ("3V","3V"),
    ("3B","3B"),
    ("3LATIN","3Latin"),
    ("3L&L1","3L&L1"),
    ("3L&L2","3L&L2"),
    ("3INTERMEDIATE1","3Intermediate1"),
    ("3INTERMEDIATE2","3Intermediate2"),
    ("3GROUPE1","3Groupe1"),
    ("3GROUPE2","3Groupe2"),
    ("3GROUPE3","3Groupe3"),
    ("3GROUPE4","3Groupe4"),
    ("3GROUPEART","3GroupeArt"),
]

class classe(models.Model):
    """
    A model for representing a class
    A class has a name, a group its assigned to, a teacher, a start and finish time and a zoom code
    """
    nom = models.CharField(max_length=127, help_text="Nom de la classe (matière)")
    classe_groupe = models.CharField(max_length=15, help_text="Classe concerné par le cours", choices=GROUPES_CHOICES)
    prof = models.CharField(max_length=31)
    commnence = models.DateTimeField()
    fini = models.DateTimeField()
    code = models.BigIntegerField(help_text="Le code du cours pour Zoom")
    link = models.CharField(max_length=255)
    posted = models.BooleanField(default=False)

    def __str__(self):
        return self.nom


class Profile(models.Model):
    """
    A model for representing a user profile
    Links to an user
    Contains class subscribed to
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    subscribed_to = models.ManyToManyField(classe, blank=True)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

codes/views.py
import datetime

import pytz 

from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect

from .models import classe, GROUPES_CHOICES

# pylint: disable=no-member

# Create your views here.
def login_view(request):    # Login page for restricteed pages
    if request.method == 'POST':
        username = "user"
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("/")
        else:
            return render(request, "codes/login.html", {"message": "Mauvais mot de passe."})
    else:
        if request.user.is_authenticated:
            return redirect("/")
        else:
            return render(request, "codes/login.html")

def logout_view(request):
    logout(request)
    return redirect("/")

@login_required
def index(request):
    """
    The view shows a blank screen with both navbars    
    """
    c = classe.objects.all().order_by('commnence')
    for i in c:
        if in_the_past(i.commnence):
            d = datetime.timedelta(days=7)
            obj = classe.objects.filter(code=i.code)
            obj.update(commnence=i.commnence+d)

    c = classe.objects.all().order_by('commnence').filter(posted=True)

    return render(request, "codes/index.html", context={"classes": c})

@login_required
def display_class(request, q="math"):
    """
    Displays a classe chosen by the user in a variable "focus"
    """
    c = classe.objects.all().order_by('commnence').filter(posted=True)
    try:
        q = int(q)
    except ValueError:
        return render(request, "codes/index.html", context={"classes": c})
    focus = []
    for i in c:
        if i.code == q:
            focus.append(i)
    if focus != []:
        return render(request, "codes/index.html", context={"classes": c, "focus": focus})
    return render(request, "codes/index.html", context={"classes": c})

@login_required
def codes(request):
    """
    Show all the codes and relevant information in a table for quick search
    """
    c = classe.objects.all().order_by('commnence').filter(posted=True)
    return render(request, "codes/codes.html", context={"classes": c})

@login_required
def soumission(request):
    if request.method == 'POST':
        nom = request.POST["nom"]
        classes = request.POST["classe_groupe"]
        prof = request.POST["prof"]
        commnence = request.POST["commnence"]
        code = request.POST["code"]
        link = request.POST["link"]
        try:
            n = classe()
            n.nom = nom
            n.classe_groupe = classes
            n.prof = prof
            n.commnence = commnence
            n.fini = commnence
            n.code = code
            n.link = link
            n.save()
            print(n)
        except Exception as e:
           print(e)
           return render(request, "codes/submit.html") 
        return redirect("codes:codes")
    else:
        return render(request, "codes/submit.html", context={"choises": GROUPES_CHOICES})

@login_required
def user_classes(request):
    if request.method == 'GET':
        if request.user.username != "user":
            all_c = classe.objects.all().order_by('commnence').filter(posted=True)
            c = request.user.profile.subscribed_to.all()
            all_g = GROUPES_CHOICES
            checked = []
            for i in request.user.profile.subscribed_to.all():
                checked.append(i.classe_groupe)

            return render(request, "codes/custom_classes.html", context={"classes": c, "all_classes": all_c, "all_g": all_g, "checked": checked})

        else:
            c = classe.objects.all().order_by('commnence').filter(posted=True)
            message = "Pour accéder a cette page, il faut s'être identifié avec un compte google"
            return render(request, "codes/codes.html", context={"classes": c, "message": message})
    else:
        checked = []
        for key in request.POST:
            checked.append(key)
        checked.pop(0) # CSRF
        request.user.profile.subscribed_to.clear()
        ac = classe.objects.all().order_by('commnence').filter(posted=True)
        for i in checked:
            for c in ac:
                if i == c.classe_groupe:
                    request.user.profile.subscribed_to.add(c)
            
        all_c = classe.objects.all().order_by('commnence').filter(posted=True)
        c = request.user.profile.subscribed_to.all()
        all_g = GROUPES_CHOICES
        return render(request, "codes/custom_classes.html", context={"classes": c, "all_classes": all_c, "all_g": all_g, "checked": checked})



def in_the_past(value):
    """
    Is the datetime object in the past (boolean)
    """
    now = datetime.datetime.now(pytz.utc)
    return value < now

def in_the_future(value):
    """
    Is the datetime object in the future (boolean)
    """
    now = datetime.datetime.now(pytz.utc)
    return value > now

codes/templates/codes/codes.html
{% extends 'codes/template.html' %}

{% block body %}
        {% load static %}
        {% load humanize %}
        {% load tags %}
        <div class="table-class">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">Matiere</th>
                        <th scope="col">Classe/Groupe</th>
                        <th scope="col">Prof</th>
                        <th scope="col">Code</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in classes %}
                        <tr>
                            <td>{{ i.nom }}</td>
                            <td>{{ i.classe_groupe }}</td>
                            <td>{{ i.prof }}</td>
                            <td><a href={{i.link}} target="_blank">{{i.code}}</a> <br></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
          
    </body>
</html>

{% endblock body %}

codes/templates/codes/custom_classes.html
{% extends 'codes/template.html' %}

{% block body %}
        {% load static %}
        {% load humanize %}
        {% load tags %}
        <div class="table-class">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">Matiere</th>
                        <th scope="col">Classe/Groupe</th>
                        <th scope="col">Prof</th>
                        <th scope="col">Code</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in classes %}
                        <tr>
                            <td>{{ i.nom }}</td>
                            <td>{{ i.classe_groupe }}</td>
                            <td>{{ i.prof }}</td>
                            <td><a href={{i.link}} target="_blank">{{i.code}}</a> <br></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <br>
        <br>    
        <button type="button" class="collapsible">Veuillez choisir les classes dans lesquelles vous êtes afin que l'on puisse vous montrez les classes qui vous sont les plus pertinentes</button>
        <div class="content">
            <form action="{% url 'codes:classes' %}" method="post" name="new">
                {% csrf_token %}
                    {% for i in all_g %}
                        {% if i.0 in checked %}
                            <input type="checkbox" name="{{i.0}}" value="{{i.0}}" class="select" checked>
                        {% else %}
                            <input type="checkbox" name="{{i.0}}" value="{{i.0}}" class="select">
                        {% endif %}
                        <label for="{{i.0}}" class="selectlabel"> {{ i.0 }}</label><br><br>
                    {% endfor %}
                <input class="submitbtn" type="submit" value="Soumettre"/>
            </form>
        </div>

          
    </body>
</html>

{% endblock body %}

codes/templates/codes/index.html
{% extends 'codes/template.html' %}

{% block body %}

        {% load static %}
        {% load humanize %}
        {% load tags %}
        <div class="wrap">


            <div id="classes" class="classes">
                {% for i in classes %}
                    {% if i.commnence|in_the_future %}
                        <div class="menu-class">
                            <a href=../c/{{i.code}} data-date="{{i.commnence}}">{{ i.nom }} - {{ i.prof }} | {{ i.commnence | naturaltime | capfirst}}</a>
                        </div>
                    {% endif %}
                {% endfor %}
                
                {% for i in classes %}
                    {% if i.commnence|in_the_past %}
                        <div class="menu-class">
                            <a href=../c/{{i.code}} data-date="{{i.commnence}}">{{ i.nom }} - {{ i.prof }} | {{ i.commnence | naturaltime | capfirst}}</a>
                        </div>
                    {% endif %}
                {% endfor %}
                <hr>
            </div>

            <div class="allFocus">
                {% for i in focus %}
                    <div class="focus">
                        {{ i.nom }}             <br>
                        {{ i.classe_groupe }}   <br>
                        {{ i.prof }}            <br>
                        {{ i.commnence|date:"l" | capfirst}} {{ i.commnence }}       <br>
                        {{ i.commnence | naturaltime | capfirst }} <br>
                        <a href={{i.link}} target="_blank">{{i.code}}</a> <br>
                        <hr style="background-color: black;">
                    </div>
                {% endfor %}
            </div>


            <div class="clear"></div>

        </div>

{% endblock %}

codes/templates/codes/login.html
<!DOCTYPE html>
<html>
    <head>
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
            <link href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round" rel="stylesheet">

            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
            {% load static %}
            <link rel="stylesheet" type="text/css" href="{% static 'codes/style.css' %}">
            <title>Login</title>
            <meta name="viewport" content="width=device-width, initial-scale=1.0">

    </head>
    <body>
        {% if message %}
            <div>
                {{ message }}
            </div>
        {% endif %}


       <div class="login-form">
           <form action="{% url 'codes:login' %}" method="post">
               {% csrf_token %}
                <h2 class="text-center">Connexion</h2>		
                <div class="text-center social-btn">
                    <a class="googlesigninbtn" href="{% url 'social:begin' 'google-oauth2' %}">
                        <img width=191px height=46px class="googlesignin" src="{% static 'codes/img/google_signin_normal.png' %}" onclick="{% url 'social:begin' 'google-oauth2' %}">
                    </a>
                </div>
                <div class="or-seperator"><i>ou</i></div>
                <div class="form-group">
					<div class="form-group">
						<input type="password" name="password" class="form-control" placeholder="Mot de passe" required="required">					
					</div>
                </div>        
                <div class="form-group">
                    <button type="submit" class="btn btn-success btn-block login-btn">Connexion</button>
                </div>
            </form>
            <div class="hint-text small">                
                    <span>S'enregistrer via Google permet la sauvegarde de vos classes dans l'onglet "mes classes".</span>
            </div>
        </div>





        <style>
            .googlesignin {
                content:url("{% static 'codes/img/google_signin_normal.png' %}");
            }

            .googlesignin:focus {
                content:url("{% static 'codes/img/google_signin_focus.png' %}");
            }

            .googlesignin:active {
                content:url("{% static 'codes/img/google_signin_pressed.png' %}");
            }

            .googlesigninbtn {
                width: 0;
                height: 0;
                border: 0;
                padding: 0;
                background-color: white;
            }
        </style>

        <style type="text/css">
            .login-form {
                width: 340px;
                margin: 30px auto;
            }
            .login-form form {
                margin-bottom: 15px;
                background: #f7f7f7;
                box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
                padding: 30px;
            }
            .login-form h2 {
                margin: 0 0 15px;
            }
            .or-seperator {
                margin: 20px 0 10px;
                text-align: center;
                border-top: 1px solid #ccc;
            }
            .or-seperator i {
                padding: 0 10px;
                background: #f7f7f7;
                position: relative;
                top: -11px;
                z-index: 1;
            }

</style>

        
   </body>
</html>

codes/templates/codes/submit.html
{% extends 'codes/template.html' %}

{% block body %}
        {% load static %}
        {% load humanize %}
        {% load tags %}

        <form action="{% url 'codes:soumission' %}" method="post" name="new">
            {% csrf_token %}
            <input name="nom" type="text" placeholder="Matiere" maxlength="127" required/><br><br>

            <select name="classe_groupe" id="classe_groupe">
                {% for i in choises %}
                <option value={{i.0}}>{{i.1}}</option>
                {% endfor %}
            </select>
            <br><br>
            <input name="prof" type="text" placeholder="Nom du professeur" maxlength="31" required/><br><br>
            <input name="commnence" type="datetime-local" required style="width: 240px;"/> <br><br>
            <input name="code" type="number" placeholder="Code" maxlength="31" required/><br><br>
            <input name="link" type="text" placeholder="Lien" maxlength="255" required/><br>
            <br>
            <input class="submitbtn" type="submit" value="Submit"/>
        </form>

        


        <style>
            body {
                background-attachment: fixed;
                background-image: url("{% static 'codes/img/donut.png' %}");
                background-position: center;
                background-repeat: no-repeat;
                background-color:rgb(116, 144, 153);
            }
        </style>

    
{% endblock body %}

codes/templates/codes/template.html
<!DOCTYPE html>
<html>
    <head>
        <title>Codes</title>

        
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        {% load static %}
        {% load humanize %}
        {% load tags %}
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static 'codes/style.css' %}">
        <script src="{% static 'codes/main.js' %}"></script>

    </head>
    <body>
        <ul class="bar">
            <li><a class="" href="/">Matières</a></li>
            <li><a href="/codes">Codes</a></li>
            <li><a href="/soumission">Soumission de codes</a></li>
            <li><a href="/classes">Mes classes</a></li>
            {% if user.first_name %}
                <li  style="float: right"><a href="/logout">Déconnexion -- {{ user.first_name }} {{ user.last_name }}</a></li>
            {% else %}
                <li  style="float: right"><a href="/logout">Déconnexion -- {{ user.username }}</a></li>
            {% endif %}
        </ul>
        {% if message %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

        {% endif %}
        <div id="time"></div>
        <div id="date"></div>

        {% block body %}
        {% endblock %}
    </body>
</html>